# Generated by Django 3.2.16 on 2022-11-30 16:54

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221129_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[users.validators.date_validator], verbose_name='День рождения'),
        ),
    ]
