# Generated by Django 3.2.16 on 2022-11-07 19:43

import Core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='Введите публикацию', verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Это идентификатор', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Идентификатор')),
                ('weight', models.PositiveSmallIntegerField(default=100, help_text='Введите вес товара', verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='Введите публикацию', verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Это идентификатор', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, help_text='Введите публикацию', verbose_name='Опубликовано')),
                ('preview', models.ImageField(upload_to='uploads/%Y/%m')),
                ('text', models.TextField(help_text='Введите описание товара', validators=[Core.validators.validate_must_be_param], verbose_name='Описание')),
                ('category', models.ForeignKey(help_text='Введите категорию товара', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(help_text='Введите теги товара, их может быть очень много', related_name='tag', to='catalog.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='uploads/%Y/%m', verbose_name='Картинка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
