# Generated by Django 3.2.16 on 2022-11-13 09:57

import django.db.models.deletion
from django.db import migrations, models

import Core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Включите, если публикация должна отображаться на главной', verbose_name='Опубликовано на главной'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Включите, если публикация должна отображаться', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='item',
            field=models.ForeignKey(help_text='Выберите товар, к которому необходимо привязать фото', on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Включите, если публикация должна отображаться', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Введите описание товара', validators=[Core.validators.validate_must_be_param], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='item',
            field=models.OneToOneField(help_text='Выберите товар, к которому необходимо привязать фото', on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='preview',
            field=models.ImageField(upload_to='uploads/%Y/%m', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Включите, если публикация должна отображаться', verbose_name='Опубликовано'),
        ),
    ]
