# Generated by Django 3.2.16 on 2022-11-27 12:31

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Введите описание товара', validators=[Core.validators.validate_must_be_param], verbose_name='Описание'),
        ),
    ]
