# Generated by Django 3.2.16 on 2022-12-05 12:57

import Core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество оценок'),
        ),
        migrations.AddField(
            model_name='item',
            name='total_rating',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Общая сумма оценок'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Введите описание товара', validators=[Core.validators.validate_must_be_param], verbose_name='Описание'),
        ),
    ]
